### ISSUE TITLE
Twitterカードをフロントエンドからデータを追加できるようにしたい

### ISSUE THREAD

**Issue by ryotarofr** [ryotarofr/one-flash#19]
## 提案
`id`を手動で入力してカードを表示させています。フロントエンドから`id`を入力したら最新の投稿が表示されるようにしたい。
```jsx
import { Tweet } from 'react-tweet';

export default function TweetPreview() {
  return <Tweet id="1741685556227293208" />;
}
```

**Comment by ZIN718** [comment]
import { Tweet } from 'react-tweet';
import React, { useState } from 'react';

export default function TweetPreview() {
  const [tweetId, setTweetId] = useState(""); // IDの状態を管理

  const handleInputChange = (event) => {
    setTweetId(event.target.value); // 入力されたIDを状態にセット
  };

  return (
    <div>
      <input type="text" value={tweetId} onChange={handleInputChange} />
      <Tweet id={tweetId} />
    </div>
  );
}

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

tweet ID はユニークだから入力したIDの表示と、モデルの最新の投稿が表示されるようにするのは別だと思うんだけど、いかが思いますか。

フロントエンドで入力するってことはユーザーが入力するってことだと思うんだけど、ユーザーがIDをとってくるイメージわかないんだけど、ご教授下さい。。。。

**Comment by ryotarofr** [comment]
>tweet ID はユニークだから入力したIDの表示と、モデルの最新の投稿が表示されるようにするのは別だと思うんだけど、いかが思いますか。
```jsx
const [tweetId, setTweetId] = useState(""); // IDの状態を管理
```
多分これじゃできなくて、データベースにPOSTする処理を書く必要があります。
最新の投稿が表示っていうのは、POSTした時にcreated_atにnow()つけてデータフェッチ後、useStateとかで持ってきたデータを.sort()すれば良いかと思っています。

>フロントエンドで入力するってことはユーザーが入力するってことだと思うんだけど、ユーザーがIDをとってくるイメージわかないんだけど、ご教授下さい。。。。
これは、スクレイピングを考えてたけどx(twitter)のポストの構造上x(twitter)のapi使わないとidだけ絞り込んで抽出するのは難しいんかな？帰ったらもうちょい調べます。

**Comment by ryotarofr** [comment]
見た感じxのポストのurlが`https://twitter.com/mia___photo/status/1742110033977245870`こんな感じで
`https://twitter.com/ユーザーネーム/status/id`でidの部分だけ持ってくることは可能そう(サイト側でブロックされなければ→CORS的なやつ)
今日は眠いから明日やる

**Comment by ryotarofr** [comment]
## 実装内容（ほぼ確定）
1. xのポスト`copy Link`してもらい`<Input />`にぶち込む
```jsx
<Input text="https://x.com/mia___photo/status/1742110033977245870?s=20" />
```
2. `status/`から`?`の間の数字だけを抽出
3. 特殊なやつはエラーで弾く(リツイートとか)
4. そのままDBへ
