### ISSUE TITLE
モデル追加してよお

### ISSUE THREAD

**Issue by ryotarofr** [ryotarofr/one-flash#26]
## 内容
所属モデル紹介ページ(/model)のモデル全部追加してないから追加してほしい

## 手順
- (リプレイス元)[https://oneflash.info/model/]から画像ファイルをローカルに保存する
保存場所: `one-flash/public/image/models` 分かりやすい名前にしてね
- データを配列に追加する
追加場所: `one-flash/config/model.ts`

**Comment by ZIN718** [comment]
完了
